import { Client } from '@notionhq/client';
import fs from 'fs';
import path from 'path';
import dotenv from 'dotenv';
import { fileURLToPath } from 'url';

// Setup basic __dirname for ES modules
const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

// Load environment variables from .env file
dotenv.config({ path: path.resolve(__dirname, '../.env') });

async function fetchConfig() {
  const notionApiKey = process.env.VITE_NOTION_API_KEY || process.env.NOTION_API_KEY;
  const blockId = process.env.VITE_NOTION_BLOCK_ID || process.env.NOTION_BLOCK_ID;

  if (!notionApiKey || !blockId) {
    console.log('⚠️ Skipping Notion fetch: Missing API Key or Block ID in .env file. Using local src/config.ts');
    return;
  }

  const notion = new Client({ auth: notionApiKey });

  try {
    console.log('☁️ Fetching layout config from Notion...');
    const response = await notion.blocks.retrieve({ block_id: blockId });
    
    if (response.type !== 'code') {
      throw new Error('The specified Notion block is not a Code Block! Please copy the ID of the exact code block.');
    }

    const jsonString = response.code.rich_text[0].plain_text;
    
    // Test if it's valid JSON
    let parsedJson;
    try {
      parsedJson = JSON.parse(jsonString);
    } catch (e) {
      throw new Error('The code block in Notion does not contain valid JSON. Please check for trailing commas or syntax errors.');
    }

    // Convert back to string and format nicely to inject into config.ts
    const finalContent = `// -----------------------------------------------------\n// AUTO-GENERATED FROM NOTION\n// Do not edit this file directly if you are using Notion!\n// -----------------------------------------------------\n\nexport const config = ${JSON.stringify(parsedJson, null, 4)};\n`;
    
    const configPath = path.resolve(__dirname, '../src/config.ts');
    fs.writeFileSync(configPath, finalContent, 'utf-8');
    
    console.log('✅ Successfully updated src/config.ts from Notion!');
  } catch (error) {
    console.error('❌ Error fetching config from Notion:', error.message);
  }
}

fetchConfig();